/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconClose: typeof import('./src/components/icons/iconClose.vue')['default']
    IconFilter: typeof import('./src/components/icons/IconFilter.vue')['default']
    IconSearch: typeof import('./src/components/icons/IconSearch.vue')['default']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SearchFilters: typeof import('./src/components/SearchFilters.vue')['default']
    SearchPagination: typeof import('./src/components/SearchPagination.vue')['default']
    SearchResults: typeof import('./src/components/SearchResults.vue')['default']
    SearchResultsSkeleton: typeof import('./src/components/SearchResultsSkeleton.vue')['default']
  }
}
